### ISSUE TITLE
tests are not passed if File::Find::Rule is not installed

### ISSUE THREAD

**Issue by zdm** [drmuey/p5-File-Copy-Recursive#15]
please, fix tests or add File::Find::Rule as dependency.

**Comment by zakame** [comment]
@zdm it is already fixed via https://github.com/drmuey/p5-File-Copy-Recursive/pull/13 but @drmuey probably hasn't made a release yet.  Hope to see a new release soon. :tada:

**Comment by drmuey** [comment]
0.42 uploaded, thanks!
