### ISSUE TITLE
Makefile.PL's `TEST_REQUIRES` requires a modern ExtUtils::MakeMaker

### ISSUE THREAD

**Issue by DrHyde** [drmuey/p5-File-Copy-Recursive#33]
File::Copy::Recursive, and anything that depends on it, won't build on a fresh install of some old versions of perl, because the EU::MM bundled with them doesn't understand TEST_REQUIRES and so the dependencies on things like Test::File and Test::Warnings won't be spotted. In particular this affects Test::File::ShareDir, which affects DateTime::Locale, which affects DateTime, which affects, well, just about everything.

The fix is to either merge TEST_REQUIRES into PREREQ_PM or, I think, declare the requirement for a modern EU::MM in META.json.

To see this bug in action, search for `Unpacking File-Copy-Recursive-0.45.tar.gz` [here](https://github.com/DrHyde/perl-modules-Palm-Treo680MessagesDB/runs/1367574859?check_suite_focus=true) and watch as it fails to build

**Comment by tomhukins** [comment]
This looks like a duplicate of #27

**Comment by DrHyde** [comment]
You're right, it is. Naughty me!
